openapi: 3.0.0
info:
  title: News Api
  description: Returns news based on given specifications.
  version: 0.0.1
servers:
  - url: http://localhost:8080
    description: Base Url for the News Api.
paths:
  /allnews:
    get:
      summary: Returns all news from all sources.
      responses:
        '200':
          description: The default response.
          content:
            text/plain:
              "Hello, world"
  /health:
    get:
      summary: Used to check the API is responsive.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: The default response.
          content:
            text/plain:
              "OK"